# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(437, 422)
        MainWindow.setMaximumSize(QtCore.QSize(437, 422))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/imagens/1200px-Cisco_logo_blue_2016.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 421, 301))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 419, 299))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbArquivo = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbArquivo.setText("")
        self.lbArquivo.setObjectName("lbArquivo")
        self.gridLayout_2.addWidget(self.lbArquivo, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 315, 37, 16))
        self.label.setObjectName("label")
        self.btArquivo = QtWidgets.QPushButton(self.centralwidget)
        self.btArquivo.setGeometry(QtCore.QRect(350, 320, 75, 23))
        self.btArquivo.setObjectName("btArquivo")
        self.btAlterar = QtWidgets.QPushButton(self.centralwidget)
        self.btAlterar.setGeometry(QtCore.QRect(270, 380, 75, 23))
        self.btAlterar.setObjectName("btAlterar")
        self.btSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btSalvar.setGeometry(QtCore.QRect(350, 350, 77, 23))
        self.btSalvar.setObjectName("btSalvar")
        self.varArquivo = QtWidgets.QLineEdit(self.centralwidget)
        self.varArquivo.setEnabled(False)
        self.varArquivo.setGeometry(QtCore.QRect(50, 320, 291, 20))
        self.varArquivo.setObjectName("varArquivo")
        self.btLimpar = QtWidgets.QPushButton(self.centralwidget)
        self.btLimpar.setGeometry(QtCore.QRect(350, 380, 75, 23))
        self.btLimpar.setObjectName("btLimpar")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 350, 47, 16))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(170, 350, 63, 16))
        self.label_8.setObjectName("label_8")
        self.varRamal = QtWidgets.QLineEdit(self.centralwidget)
        self.varRamal.setGeometry(QtCore.QRect(50, 350, 101, 20))
        self.varRamal.setObjectName("varRamal")
        self.varSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.varSenha.setGeometry(QtCore.QRect(210, 350, 101, 20))
        self.varSenha.setObjectName("varSenha")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XML"))
        self.label.setText(_translate("MainWindow", "Arquivo"))
        self.btArquivo.setText(_translate("MainWindow", "Abrir Arquivo"))
        self.btAlterar.setText(_translate("MainWindow", "Alterar"))
        self.btSalvar.setText(_translate("MainWindow", "Salvar arquivo"))
        self.btLimpar.setText(_translate("MainWindow", "Limpar"))
        self.label_6.setText(_translate("MainWindow", "Ramal:"))
        self.label_8.setText(_translate("MainWindow", "Senha:"))
